import {
  Fulfillment,
  isUniqueViolation,
  OrderStatus,
  PaymentMethod,
  Prisma,
  prisma,
} from "@workspace/db"
import { z } from "zod"

import {
  MAX_LINES_PER_ORDER,
  MAX_QTY_PER_LINE,
  MIN_ONLINE_PAYMENT_PAISE,
  TEXT_LIMITS,
} from "../constants"
import { DomainError } from "../errors"
import { isWithinRadius } from "../locations/distance"
import { isOpenAt, openingHoursSchema } from "../locations/hours"
import { notifyOrderStatus } from "../notifications/order-status"
import { calculateTotals, priceLines } from "../pricing"

// What the browser is allowed to send. Note what is missing: prices, totals,
// status and the customer id. The server works those out itself.
export const placeOrderInput = z
  .object({
    restaurantId: z.uuid(),
    locationId: z.uuid(),
    fulfillment: z.enum(Fulfillment),
    paymentMethod: z.enum(PaymentMethod),
    customerName: z.string().trim().min(1).max(TEXT_LIMITS.customerName),
    address: z
      .object({
        line1: z.string().trim().min(3).max(TEXT_LIMITS.addressLine),
        landmark: z.string().trim().max(TEXT_LIMITS.landmark).optional(),
        lat: z.number().min(-90).max(90),
        lng: z.number().min(-180).max(180),
      })
      .optional(),
    items: z
      .array(
        z.object({
          menuItemId: z.uuid(),
          qty: z.number().int().min(1).max(MAX_QTY_PER_LINE),
        })
      )
      .min(1)
      .max(MAX_LINES_PER_ORDER),
    // Generated by the browser once per checkout attempt.
    idempotencyKey: z.string().min(8).max(TEXT_LIMITS.idempotencyKey),
  })
  .refine((o) => o.fulfillment === Fulfillment.pickup || o.address, {
    message: "A delivery address is required.",
    path: ["address"],
  })

export type PlaceOrderInput = z.infer<typeof placeOrderInput>

const withItems = { items: true } as const

export async function placeOrder(
  customerId: string,
  rawInput: unknown,
  now = new Date()
) {
  const parsed = placeOrderInput.safeParse(rawInput)
  if (!parsed.success) {
    throw new DomainError(
      "INVALID_INPUT",
      parsed.error.issues[0]?.message ?? "Invalid order."
    )
  }
  const input = parsed.data

  // Same checkout attempt submitted again (double click, network retry).
  const existing = await prisma.order.findUnique({
    where: {
      customerId_idempotencyKey: {
        customerId,
        idempotencyKey: input.idempotencyKey,
      },
    },
    include: withItems,
  })
  if (existing) return existing

  const location = await prisma.location.findFirst({
    where: { id: input.locationId, restaurantId: input.restaurantId },
    include: { restaurant: true },
  })
  if (!location)
    throw new DomainError("NOT_FOUND", "This outlet does not exist.")

  const hours = openingHoursSchema.parse(location.hours)
  if (!location.isOpen || !isOpenAt(hours, now)) {
    throw new DomainError(
      "LOCATION_CLOSED",
      `${location.name} is closed right now.`
    )
  }
  if (input.fulfillment === Fulfillment.pickup && !location.acceptsPickup) {
    throw new DomainError(
      "FULFILLMENT_NOT_AVAILABLE",
      `${location.name} does not offer pickup.`
    )
  }
  if (
    input.fulfillment === Fulfillment.delivery &&
    (!input.address ||
      !isWithinRadius(location, input.address, location.deliveryRadiusM))
  ) {
    throw new DomainError(
      "OUT_OF_RANGE",
      `This address is outside ${location.name}'s delivery area.`
    )
  }
  if (input.paymentMethod === PaymentMethod.cod && !location.acceptsCod) {
    throw new DomainError(
      "PAYMENT_METHOD_NOT_AVAILABLE",
      `${location.name} does not accept cash.`
    )
  }

  // Merge repeated items, then load real prices from the database.
  const qtyById = new Map<string, number>()
  for (const item of input.items) {
    qtyById.set(item.menuItemId, (qtyById.get(item.menuItemId) ?? 0) + item.qty)
  }
  const menuItems = await prisma.menuItem.findMany({
    where: {
      id: { in: [...qtyById.keys()] },
      restaurantId: input.restaurantId,
      archivedAt: null,
    },
  })
  const unavailable = [...qtyById.keys()].filter(
    (id) => !menuItems.some((m) => m.id === id && m.isAvailable)
  )
  if (unavailable.length > 0) {
    throw new DomainError(
      "ITEM_UNAVAILABLE",
      "Some items in your cart are no longer available."
    )
  }

  const lines = priceLines(
    menuItems.map((m) => ({
      menuItemId: m.id,
      title: m.title,
      unitPricePaise: m.pricePaise,
      qty: qtyById.get(m.id) ?? 0,
    }))
  )
  const totals = calculateTotals(lines, input.fulfillment, location)
  if (
    input.paymentMethod === PaymentMethod.online &&
    totals.totalPaise < MIN_ONLINE_PAYMENT_PAISE
  ) {
    // Razorpay cannot take payments below ₹1.
    throw new DomainError(
      "INVALID_INPUT",
      "Online payment needs an order of at least ₹1."
    )
  }

  const customer = await prisma.profile.findUnique({
    where: { id: customerId },
  })
  if (!customer?.phone)
    throw new DomainError("NOT_FOUND", "Customer profile not found.")

  let order
  try {
    order = await prisma.order.create({
      data: {
        restaurantId: input.restaurantId,
        locationId: location.id,
        customerId,
        status:
          input.paymentMethod === PaymentMethod.cod
            ? OrderStatus.PLACED
            : OrderStatus.PENDING_PAYMENT,
        fulfillment: input.fulfillment,
        paymentMethod: input.paymentMethod,
        customerName: input.customerName,
        customerPhone: customer.phone,
        deliveryAddress:
          input.fulfillment === Fulfillment.delivery
            ? input.address
            : Prisma.DbNull,
        ...totals,
        idempotencyKey: input.idempotencyKey,
        items: {
          create: lines.map((l) => ({
            menuItemId: l.menuItemId,
            title: l.title,
            unitPricePaise: l.unitPricePaise,
            qty: l.qty,
            lineTotalPaise: l.lineTotalPaise,
          })),
        },
      },
      include: withItems,
    })
  } catch (error) {
    // Two identical submits raced past the check above; the unique
    // (customer_id, idempotency_key) index let only one insert through.
    if (isUniqueViolation(error)) {
      return prisma.order.findUniqueOrThrow({
        where: {
          customerId_idempotencyKey: {
            customerId,
            idempotencyKey: input.idempotencyKey,
          },
        },
        include: withItems,
      })
    }
    throw error
  }

  if (order.status === OrderStatus.PLACED) {
    await notifyOrderStatus(order, location.restaurant.name)
  }
  return order
}
